### ISSUE TITLE
[Bug]: config.py error MacOS Big Sur

### ISSUE THREAD

**Issue by sushantvema** [obsidianMkdocs/obsidian-mkdocs-publisher-template#8]
### Describe the bug

Running obs2mk with python version 3.9.12 via conda environment, I get the following error: 

Traceback (most recent call last):
  File "/Users/sashikanth/opt/anaconda3/envs/tru-env/bin/obs2mk", line 5, in <module>
    from mkdocs_obsidian.__main__ import main
  File "/Users/sashikanth/opt/anaconda3/envs/tru-env/lib/python3.9/site-packages/mkdocs_obsidian/__main__.py", line 12, in <module>
    from mkdocs_obsidian.common.config import Configuration
  File "/Users/sashikanth/opt/anaconda3/envs/tru-env/lib/python3.9/site-packages/mkdocs_obsidian/common/config.py", line 19, in <module>
    class Configuration:
  File "/Users/sashikanth/opt/anaconda3/envs/tru-env/lib/python3.9/site-packages/mkdocs_obsidian/common/config.py", line 22, in Configuration
    output: str | Path,
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### How to reproduce ?

1. cd into my top level directory of my Obsidian vault
2. create conda environment
3. use pip to install obs2mk
4. make sure python version is 3.9.12 
5. run the following in terminal: obs2mk
6. observe the above error

**Comment by Mara-Li** [comment]
Yeah, the plugin needs 3.10

**Comment by Mara-Li** [comment]
Also, please, use the right repo for problem with the python package...
